### ISSUE TITLE
Consistent terminology: `T2S..` -> `TS2...`, etc

### ISSUE THREAD

**Issue by michaelsaxon** [michaelsaxon/T2IScoreScore#11]
We should move all these `T2S...` to `TS2...` but for now it's not a priority

> Good to remove Halluvision references but we need more cleaning. This is not a priority but should eventually be addressed (can wait until after paper submission)

_Originally posted by @michaelsaxon in https://github.com/michaelsaxon/T2IScoreScore/pull/8#discussion_r1479351152_

**Comment by Arenaa** [comment]
Fixed the issue
